import '../globals.css'
export const metadata = {
  title: 'Reach out to us',
  description: 'Generated by vaxad',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}
